services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    environment:
      - CHROMA_DIR=/app/data/chroma_db
      - MEDICAL_DOCS_DIR=/app/data/medical_docs
    #ports:
    #  - "8000:8000"
    networks:
      - app_network
    volumes:
      - backend_uploads:/app/uploads
      - chroma_db:/app/data/chroma_db
      - model_cache:/root/.cache/huggingface
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  backend_uploads:
  chroma_db:
  model_cache: